# Provided here are several examples that can be used to test the API that it is functioning correctly when running on the localhost.
#
# To make use of this file, you can use the REST Client extension for Visual Studio Code:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###########################
# Swagger/Swashbuckle Test
# =========================
GET http://localhost:5000/swagger

# GET Tests
######################
# SL
# ====================
GET http://localhost:5000/Calculate/SL
?PurchasePrice=1000
&Residual=0
&Life=5
&AssetName=SlAsset

######################
# DDB
# ====================
GET http://localhost:5000/Calculate/DB200
?PurchasePrice=1000
&Residual=0&Life=5
&AssetName=DdbAsset

######################
# SYD
# ====================
GET http://localhost:5000/Calculate/SYD
?PurchasePrice=1000
&Residual=0
&Life=5
&AssetName=DdbAsset

######################
# MACRS-HY
# ====================
GET http://localhost:5000/Calculate/MACRSHY
?PurchasePrice=1000
&Life=5
&Section179=200
&AssetName=MacrsHyAsset
&PurchaseDate=10%2F01%2F2020

######################
# MACRS-MQ
# ====================
GET http://localhost:5000/Calculate/MACRSMQ
?PurchasePrice=1000
&Life=5
&Section179=200
&AssetName=MacrsMqAsset
&PurchaseDate=10%2F01%2F2020

#############################
# MACRS-HY - INVALID TAX YEAR 
# ===========================
GET http://localhost:5000/Calculate/MACRSHY
?PurchasePrice=1000
&Life=9
&Section179=200
&AssetName=MacrsHyAsset
&PurchaseDate=10%2F01%2F2020

###############################
# MACRS-MQ - INVALID ERROR YEAR
# =============================
GET http://localhost:5000/Calculate/MACRSMQ
?PurchasePrice=1000
&Life=59
&Section179=200
&AssetName=MacrsMqAsset
&PurchaseDate=10%2F01%2F2020

#################################
# Full Calculation via JSON POST
# ===============================
POST http://localhost:5000/Calculate/Depreciate
Content-Type: application/json

{
  "name": "New Asset",
  "purchaseDate": "2011-01-01",
  "purchasePrice": 1000,
  "residualValue": 0,
  "section179": 0,
  "usefulLife": 5,
  "taxLife": 5,
  "GaapMethod": "SL",
  "TaxMethod": "MACRSHY"
}

####
# Example POST sending a URL via post - BASIC AUTHENTICATION
POST http://localhost:5000/Calculate/Depreciate
Content-Type: application/json
Content-Type: text/plain
Authorization: Basic testUser:testPassword

{
  "name": "New Asset",
  "purchaseDate": "2011-01-01",
  "purchasePrice": 1000,
  "residualValue": 0,
  "section179": 0,
  "usefulLife": 5,
  "taxLife": 7,
  "GaapMethod": "SL",
  "TaxMethod": "MACRSHY"
}


############################################
# Full Array/Batch Calculation via JSON POST
# ==========================================
POST http://localhost:5000/Calculate/DepreciateArray
Content-Type: application/json

[
  {
    "name": "New Asset",
    "purchaseDate": "2011-01-01",
    "purchasePrice": 1000,
    "residualValue": 0,
    "section179": 0,
    "usefulLife": 5,
    "taxLife": 5,
    "GaapMethod": "SL",
    "TaxMethod": "MACRSHY"
  },
  {
    "name": "New Asset 2",
    "purchaseDate": "2001-01-01",
    "purchasePrice": 2000,
    "residualValue": 0,
    "section179": 0,
    "usefulLife": 7,
    "taxLife": 7,
    "GaapMethod": "DB200",
    "TaxMethod": "MACRSMQ"
  }
]
