# Provided here are several examples that can be used to test the API that it is functioning correctly when running on the localhost.

# GET Tests
######################
# SL
# ====================
GET http://localhost:5000/Calculate/SL?PurchasePrice=1000&Residual=0&Life=5&AssetName=SlAssest

######################
# DDB
# ====================
GET http://localhost:5000/Calculate/DB200?PurchasePrice=1000&Residual=0&Life=5&AssetName=DdbAsset

######################
# MACRS-HY
# ====================
GET http://localhost:5000/Calculate/MACRSHY?PurchasePrice=1000&Life=5&Section179=200&AssetName=MacrsHyAsset

######################
# MACRS-MQ
# ====================
GET http://localhost:5000/Calculate/MACRSMQ?PurchasePrice=1000&Life=5&Section179=200&AssetName=MacrsMqAsset&PurchaseDate=10%2F01%2F2020