# This is a basic workflow to help you get started with Actions

name: Manual Build

# Controls when the workflow will run
on:
  # Forcing it to run on the initial PR
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install DotNet 5 SDK
      - name: Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Generate a PAT with package read rights only
      # https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
      # Store the PAT in a repo Secret (here saved as NUGET_PAT)
      
      # Use the PAT as the password and the ORG or USER name for the username
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-with-github_token-in-github-actions
      - name: dotnet nuget add source
        run: dotnet nuget add source --username joelbyford --password ${{secrets.NUGET_PAT}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/joelbyford/index.json"
        
      # Restore Dependancies (can be omitted is you remove --no-restore on build step)
      - name: Restore package dependencies
        run: dotnet restore

      # Build the project
      - name: dotet build
        run: dotnet build --no-restore --configuration Release
